apiVersion: v2
name: sealed-secrets
description: A Helm chart for kyverno deployment
type: application
dependencies:
  - name: sealed-secrets
    repository:  "https://bitnami-labs.github.io/sealed-secrets/"
